# For standard Spring Boot parameters see:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
server:
  port: 8888
  servlet:
    context-path:
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: rest-api-example1-service
        uri: http://localhost:8080
        predicates:
        - Path=/rest-api-example1/**
      - id: rest-api-example2-service
        uri: http://localhost:8081
        predicates:
        - Path=/rest-api-example2/**
      - id: rest-api-example-m2m-service
        uri: http://localhost:8082
        predicates:
        - Path=/rest-api-example-m2m/**        
      - id: openapi
        uri: http://localhost:${server.port}
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs